name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y afl++

      - name: Compile with AFL++
        run: |
          CC=afl-gcc CXX=afl-g++ make clean all

      - name: Prepare input for fuzzing
        run: |
          mkdir afl_input
          cp testcases/valid/*.gft afl_input/
          cp testcases/invalid/*.gft afl_input/

      - name: Run AFL++ Fuzzer
        run: |
          afl-fuzz -i afl_input -o afl_output -M fuzzer1 ./giftcardreader 1 @@ &
          afl-fuzz -i afl_input -o afl_output -S fuzzer2 ./giftcardreader 1 @@ &
          afl-fuzz -i afl_input -o afl_output -S fuzzer3 ./giftcardreader 1 @@
          
      - name: Collect results
        run: |
          echo "Fuzzing results:"
          ls afl_output